# secrets.toml
[openai]
api_key = "sk-proj-2oGJeulKtGcPmajbPdfyT3BlbkFJMfDthqEvcRkI8A1DPWN5"

[servicenow]
instance_url = " https://dev274828.service-now.com/"
username = "aes.creator"
password = "/N3-Ekw6XUgc"